# Generated by Django 4.1.1 on 2022-10-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='udated_date',
            new_name='updated_date',
        ),
    ]
