# Generated by Django 4.1.1 on 2022-10-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrimage',
            name='image',
            field=models.ImageField(upload_to='static/images/<django.db.models.fields.CharField>'),
        ),
    ]
