# Generated by Django 4.1.1 on 2022-10-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0002_alter_qrimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qrimage',
        ),
    ]
