# Generated by Django 4.1.1 on 2022-10-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qrcodeapp', '0003_delete_qrimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img_name', models.CharField(default='new', max_length=200)),
                ('qr_img', models.ImageField(upload_to='static/images/qrcodes/')),
            ],
        ),
    ]
